[package]
name = "filesyscall_catch"
version = "0.1.0"
edition = "2021"

[dependencies]
libbpf-rs = "0.22"
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
libc = "0.2"

[build-dependencies]
libbpf-cargo = "0.22"